### ISSUE TITLE
chunks storing in 2 locations

### ISSUE THREAD

**Issue by elevenpast** [FineUploader/node-fine-uploader-server#7]
For some reason, chunk files are being stored in 2 locations,  <uploadedFilesPath>/chunks and also in /tmp.  So if I upload a 2GB file, it ends up taking 4GB on the server. 

I cannot figure out why the chunks are being written to /tmp.   Any ideas?

Josh

**Comment by rnicholus** [comment]
This library is no longer maintained. Please see the notice in the readme
